version: "3.7"

services:
  javascript_env:
    image: node:12-alpine
  docs:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8000:8000
    volumes:
      - ./:/app
