version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - store_test_results:
          path: test-results


workflows:
  say-hello-workflow:
    jobs:
      - node/test

