
# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.0
      - image: cimg/mysql:5.7
    steps:
      - checkout
      - node/install-packages:
        app-dir: app
      - run: npm install