version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable

    steps:
      - node/install-npm
      - checkout
      - node/install-packages:
          app-dir: app
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run: npm test
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
