version: '2.1'
orbs:
  node: circleci/node@5.0.3
  test:
    executor: node/default
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/app/node_modules
          override-ci-command: npm install
      - run: npm test
