version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-npm
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run: npm test
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
